#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"

//// end generated include

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
	protected:
		// Handlers for GUIClass events.
		void OnStartup( wxActivateEvent& event );
		void OnExitSelected( wxCommandEvent& event );
		void OnGameButtonClick( wxCommandEvent& event );
		void OnResetClick( wxCommandEvent& event );

		// initializes gameBoard
		void PopulateGameBoard();
		// resets gameBoard
		void ResetBoard();
		// self explanitory
		std::string CheckForWinner();

	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
	//// end generated class members
	
};

#endif // __SubGUIClass__
